#!/bin/bash
# =============================================================================
# FILE: aws/scripts/deploy-frontend.sh
# PURPOSE: Builds the React/Vite frontend and deploys it to AWS S3 + CloudFront.
#
# WHAT THIS DOES:
#   1. Runs 'npm run build' in the frontend/ directory (creates dist/ folder)
#   2. Syncs the dist/ folder to the S3 bucket (created by 05-s3-cloudfront.yaml)
#   3. Invalidates CloudFront cache so users see the latest version immediately
#
# CURRENT SETUP: Frontend is on Vercel (see frontend/.env.production VITE_API_URL)
# NEW SETUP: Frontend is on S3 + CloudFront
#
# USAGE:
#   bash aws/scripts/deploy-frontend.sh
#
# PREREQUISITES:
#   1. Run 05-s3-cloudfront.yaml first to create S3 bucket and CloudFront
#   2. Update frontend/.env.production VITE_API_URL to point to ALB endpoint
#   3. Node.js 18+ installed
#   4. AWS CLI configured with S3 write permissions
# =============================================================================

set -e  # Exit on any error

# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION — Update these after deploying 05-s3-cloudfront.yaml
# Get S3 bucket name from stack output:
#   aws cloudformation describe-stacks --stack-name grocery-frontend
#   --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" --output text
# ─────────────────────────────────────────────────────────────────────────────

AWS_REGION="ap-south-1"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

# S3 Bucket name for frontend (from 05-s3-cloudfront.yaml output)
S3_BUCKET="grocery-store-frontend-${AWS_ACCOUNT_ID}"

# CloudFront Distribution ID (from 05-s3-cloudfront.yaml output)
# Get it: aws cloudformation describe-stacks --stack-name grocery-frontend
#         --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text
CLOUDFRONT_DISTRIBUTION_ID="REPLACE_WITH_YOUR_DISTRIBUTION_ID"

# Backend API URL — ALB DNS from 04-ecs-fargate.yaml
# Get it: aws cloudformation describe-stacks --stack-name grocery-ecs
#         --query "Stacks[0].Outputs[?OutputKey=='ALBDnsName'].OutputValue" --output text
# This is the VITE_API_URL that the React app uses to call the backend
BACKEND_API_URL="https://REPLACE_WITH_ALB_DNS_NAME"

# Path to frontend directory (relative to project root)
FRONTEND_DIR="$(dirname "$0")/../../frontend"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1: Validate configuration
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo "Online Grocery Store — Frontend Deployment to AWS"
echo "=================================================="
echo ""
echo "Configuration:"
echo "  S3 Bucket:        ${S3_BUCKET}"
echo "  CloudFront ID:    ${CLOUDFRONT_DISTRIBUTION_ID}"
echo "  Backend API URL:  ${BACKEND_API_URL}"
echo ""

# Warn if CloudFront ID hasn't been updated
if [ "${CLOUDFRONT_DISTRIBUTION_ID}" = "REPLACE_WITH_YOUR_DISTRIBUTION_ID" ]; then
    echo "❌ ERROR: CLOUDFRONT_DISTRIBUTION_ID not configured!"
    echo "   1. Deploy 05-s3-cloudfront.yaml first"
    echo "   2. Get Distribution ID from stack output"
    echo "   3. Update CLOUDFRONT_DISTRIBUTION_ID in this script"
    exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2: Set environment variables for the React build
# The Vite build reads from .env.production but we override VITE_API_URL
# to point to the AWS ALB instead of the old server.
# ─────────────────────────────────────────────────────────────────────────────
echo "=================================================="
echo "STEP 2: Configuring environment for AWS build..."
echo "=================================================="

cd "${FRONTEND_DIR}"

# Create a temporary production environment file for AWS
# This overrides frontend/.env.production for this build
# The original frontend/.env.production is UNTOUCHED (pointing to Vercel/old server)
cat > .env.production.aws << EOF
# ============================================================
# AWS Production Environment File (TEMPORARY - for AWS build)
# This file is generated by aws/scripts/deploy-frontend.sh
# It overrides the default .env.production for AWS deployments
# DO NOT commit this file to git!
# ============================================================

# Backend API URL — points to AWS ALB (not Vercel or local server)
VITE_API_URL=${BACKEND_API_URL}

# Google OAuth Client ID (same for all environments)
# Get from: Google Cloud Console → APIs & Services → Credentials
VITE_GOOGLE_CLIENT_ID=REPLACE_WITH_YOUR_GOOGLE_CLIENT_ID

# Google Maps API Key (if used in the grocery store app)
VITE_GOOGLE_MAPS_API_KEY=REPLACE_WITH_YOUR_GOOGLE_MAPS_KEY
EOF

echo "✅ AWS environment file created (.env.production.aws)"
echo "   VITE_API_URL set to: ${BACKEND_API_URL}"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3: Install dependencies (if node_modules missing)
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo "STEP 3: Checking dependencies..."
echo "=================================================="

if [ ! -d "node_modules" ]; then
    echo "node_modules missing — installing dependencies..."
    npm ci  # 'npm ci' is faster and more reliable than 'npm install' for CI/CD
    echo "✅ Dependencies installed"
else
    echo "✅ node_modules exists — skipping install"
fi

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4: Build the React/Vite app for production
# 'npm run build' = 'tsc -b && vite build' (from frontend/package.json)
# Output goes to: frontend/dist/ folder
# Vite generates hashed filenames for cache-busting: main.abc123.js
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo "STEP 4: Building React/Vite app for production..."
echo "This TypeScript compilation + Vite bundle may take 1-2 minutes."
echo "=================================================="

# Use the AWS-specific environment file
# Vite will use .env.production.aws if it exists (it takes precedence)
# This sets VITE_API_URL to the ALB endpoint for the build
VITE_API_URL="${BACKEND_API_URL}" npm run build

# Remove the temporary AWS env file after build
rm -f .env.production.aws

echo ""
echo "✅ Build complete!"
echo "   Output: frontend/dist/"
ls -la dist/ | head -10

# Show build sizes
echo ""
echo "📦 Bundle sizes:"
du -sh dist/assets/*.js 2>/dev/null | sort -k1 -h | tail -5 || true

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5: Upload build files to S3
# 'aws s3 sync' uploads only changed files (faster than full re-upload)
# --delete: remove files from S3 that no longer exist in dist/
# Cache-Control headers:
#   - JS/CSS files have content hashes → cache for 1 year (immutable)
#   - index.html has no hash → never cache (always get latest)
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo "STEP 5: Uploading files to S3 bucket..."
echo "Bucket: s3://${S3_BUCKET}/"
echo "=================================================="

# Upload index.html with "no-cache" — always fetch fresh from server
# This ensures users always get the latest app entry point
aws s3 cp dist/index.html "s3://${S3_BUCKET}/index.html" \
    --region "${AWS_REGION}" \
    --cache-control "no-cache, no-store, must-revalidate" \
    --content-type "text/html"

echo "✅ index.html uploaded (no-cache)"

# Upload hashed JS/CSS/image assets with long cache (1 year = 31536000 seconds)
# Vite generates filenames like: main.BcD3xY8z.js — these are immutable
# Users can safely cache these for a full year
aws s3 sync dist/ "s3://${S3_BUCKET}/" \
    --region "${AWS_REGION}" \
    --exclude "index.html" \
    --cache-control "public, max-age=31536000, immutable" \
    --delete \
    --no-progress

echo "✅ Assets uploaded to S3 (cached for 1 year)"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6: Invalidate CloudFront Cache
# After uploading new files to S3, CloudFront might still serve old cached files.
# An invalidation tells CloudFront to clear its cache and fetch fresh files from S3.
# Invalidation cost: first 1000 invalidations/month free, then $0.005 each
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo "STEP 6: Invalidating CloudFront cache..."
echo "Distribution: ${CLOUDFRONT_DISTRIBUTION_ID}"
echo "=================================================="

# Invalidate ALL files (/* means everything in the distribution)
# For efficiency, you could invalidate only changed files
INVALIDATION_ID=$(aws cloudfront create-invalidation \
    --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
    --paths "/*" \
    --query "Invalidation.Id" \
    --output text)

echo "✅ CloudFront invalidation created: ${INVALIDATION_ID}"
echo "   Cache will clear within 1-5 minutes globally"
echo "   Check status: aws cloudfront get-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --id ${INVALIDATION_ID}"

# ─────────────────────────────────────────────────────────────────────────────
# STEP 7: Get the CloudFront URL to access the deployed app
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo "🎉 Frontend Deployment Complete!"
echo "=================================================="

# Get CloudFront domain from AWS
CF_DOMAIN=$(aws cloudfront get-distribution \
    --id "${CLOUDFRONT_DISTRIBUTION_ID}" \
    --query "Distribution.DomainName" \
    --output text 2>/dev/null || echo "Check AWS Console")

echo ""
echo "🌐 Frontend is live at:"
echo "   https://${CF_DOMAIN}"
echo ""
echo "📊 S3 Bucket contents:"
echo "   aws s3 ls s3://${S3_BUCKET}/"
echo ""
echo "🔧 To view CloudFront distribution:"
echo "   https://console.aws.amazon.com/cloudfront/v3/home#/distributions/${CLOUDFRONT_DISTRIBUTION_ID}"
echo ""
echo "⏳ Note: CloudFront cache invalidation takes 1-5 minutes to propagate globally."
echo "   Users may see the old version for a few minutes — this is normal."
echo ""
